### ISSUE TITLE
Documentation and code are inconsistent

### ISSUE THREAD

**Issue by five-wang** [nolantait/pong-tutorial#1]
https://taintedcoders.com/bevy/pong-tutorial/#creating-a-ball
The code for the document looks like this
![image](https://github.com/nolantait/pong-tutorial/assets/66893381/7b9b9211-d669-4cbe-b433-6c6ca450b403)

rust pattern matches error

**Comment by nolantait** [comment]
I've fixed this in the 0.14 update so closing now. Thanks for pointing this out.

**Comment by nolantait** [comment]
I've fixed this in the 0.14 update so closing now. Thanks for pointing this out.
